### ISSUE TITLE
添加多租户、分离core包

### ISSUE THREAD

**Issue by klniu** [wuyouzhuguli/FEBS-Vue#11]
多谢大神的框架，找了好久，才发现这个合适的。
请问不知能否向代码中添加多租户代码？
能否将common、job、system包分离出来作成一个包，可以打成一个jar，这样可以在后期的项目中直接使用？
如果可以，我可以提交一个pr，您审核，麻烦您了。

**Comment by wuyouzhuguli** [comment]
你好，这项修改可能不适合大部分人，pr可能不太合适。😀

**Comment by klniu** [comment]
明白，我在fork里自己加了，多谢。

**Comment by wuyouzhuguli** [comment]
🤝
