### ISSUE TITLE
sql count 问题

### ISSUE THREAD

**Issue by NsirNixp** [wuyouzhuguli/FEBS-Vue#18]
貌似换成mybatisplus之后，用户页面报错
![image](https://user-images.githubusercontent.com/18341792/54881882-a78f7f80-4e8f-11e9-9e40-3bd3b9d52e60.png)

**Comment by wuyouzhuguli** [comment]
点击用户管理报错么，本地试了没出现问题，可以给出具体的环境信息么

**Comment by NsirNixp** [comment]
找到问题了，我mysql  sql_mode 设置有问题，从8.0 降到5.7之后没有重新设置
