### ISSUE TITLE
怎么添加“不直接在侧边栏展示的”菜单？

### ISSUE THREAD

**Issue by Godykc** [wuyouzhuguli/FEBS-Vue#21]
有些页面比如一个详情页，如果是一个复杂表单的话，就不适合直接弹层展示
这时候也不适合新加一个页面菜单，因为加了之后就直接展示在侧边栏了，用户点进去没法展示

所以 这种场景下 要加一个复杂表单的详情页怎么加？
作者可以给个例子么

**Comment by wuyouzhuguli** [comment]
可以使用抽屉，就是现在增加修改的页面。抽屉宽度设置宽一点就好了。

**Comment by Godykc** [comment]
> 可以使用抽屉，就是现在增加修改的页面。抽屉宽度设置宽一点就好了。

那如果就是要新开一个页面呢？
是不是要大改了，
我看了下路由是存在localstorage的，
那里面的页面好像都会在侧边栏展示出来

**Comment by wuyouzhuguli** [comment]
路由菜单meta里面可以指定是否显示，比如个人中心这个路由就没有在菜单那里显示。

**Comment by Godykc** [comment]
> 路由菜单meta里面可以指定是否显示，比如个人中心这个路由就没有在菜单那里显示。

好的，我再看看
