### ISSUE TITLE
前端安装chromedriver报错

### ISSUE THREAD

**Issue by mseaspring** [wuyouzhuguli/FEBS-Vue#22]
您好，在运行yarn install过程中，有报错：PS E:\workjava\febs\FEBS-Vue\frontend> yarn install
yarn install v1.15.2
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[1/2] ⠁ uglifyjs-webpack-plugin
error E:\workjava\febs\FEBS-Vue\frontend\node_modules\chromedriver: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: E:\workjava\febs\FEBS-Vue\frontend\node_modules\chromedriver
Output:
Downloading https://chromedriver.storage.googleapis.com/2.40/chromedriver_win32.zip
Saving to C:\Users\Think\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
ChromeDriver installation failed Error with http(s) request: Error: read ECONNRESET

自己下载了放进去也不行，请教下有什么好办法，我看了下文档没有这方面内容。谢谢

**Comment by wuyouzhuguli** [comment]
删掉node modules重新下载，多试几次。有条件的话可以科学上网。

**Comment by mseaspring** [comment]
谢谢，自己下载的，有没有办法直接使用- - 试了几次都不行，麻烦了

**Comment by wuyouzhuguli** [comment]
yarn install 出现长时间等待或者你这种情况，可以直接yarn start看看是否可以正常运行。我这边可以正常下载依赖，实在不行换个网络环境试试。

**Comment by mseaspring** [comment]
谢谢已经可以了，非常感谢提供这么好的系统

**Comment by wuyouzhuguli** [comment]
不客气，喜欢的话可以点个star鼓励作者。
