### ISSUE TITLE
SQL日志输出

### ISSUE THREAD

**Issue by xiaoba28** [wuyouzhuguli/FEBS-Vue#23]
如果我把p6spy: true设置为false  那么删除相应的代码、配置文件  系统应该不会受影响 依旧可以运行吧

**Comment by wuyouzhuguli** [comment]
不会，如果不想要这个功能，配置去掉就好，因为默认就是false。

**Comment by xiaoba28** [comment]
好的  谢谢博主  有问题再来探讨
