### ISSUE TITLE
前端的localStorage.js get 方法取不到 0

### ISSUE THREAD

**Issue by luneshao** [wuyouzhuguli/FEBS-Vue#25]
```
// 文件路径
/frontend/src/utils/localstorage.js
```

当 `localStorage` `ls.save('name', 0)` 方法存的值为 0 时， `ls.get('name', false)` 会取到 `false`。

**Comment by wuyouzhuguli** [comment]
```javascript
0 || false // false
'0'|| false // '0'
```

**Comment by wuyouzhuguli** [comment]
如果执意要存0的话，可以改一下localstorage.js中的get方法。

**Comment by wuyouzhuguli** [comment]
```javascript
get (key, defaultValue = {}) {
   if (JSON.parse(localStorage.getItem(key)) === 0) {
       return 0;
   }
   return JSON.parse(localStorage.getItem(key)) || defaultValue
},
```

**Comment by luneshao** [comment]
> ```js
> get (key, defaultValue = {}) {
>    if (JSON.parse(localStorage.getItem(key)) === 0) {
>        return 0;
>    }
>    return JSON.parse(localStorage.getItem(key)) || defaultValue
> },
> ```

谢谢大佬
