### ISSUE TITLE
跨系统运行可能会出现的一个错误

### ISSUE THREAD

**Issue by mxbq** [wuyouzhuguli/FEBS-Vue#29]
https://github.com/wuyouzhuguli/FEBS-Vue/blob/fb226f158daba9352ac22413b57e01e154244d52/backend/src/main/java/cc/mrbird/febs/common/service/impl/RedisServiceImpl.java#L51

https://github.com/wuyouzhuguli/FEBS-Vue/blob/fb226f158daba9352ac22413b57e01e154244d52/backend/src/main/java/cc/mrbird/febs/common/service/impl/RedisServiceImpl.java#L93

不同系统的换行符不同，Windows上为：\r\n ，Linux上为：\n ，Unix上为：\r 。
建议使用下一行Java语句动态获取系统中的换行符：
System.getProperty("line.separator")

可能出现的问题：Windows上用字符 \n 分隔字符串后，会留下字符 \r 在字符串末尾， \r （回车，使光标到行首）后输出字符，会出现覆盖之前语句的情况

**Comment by wuyouzhuguli** [comment]
谢谢，已修复
