### ISSUE TITLE
后端所有类的log打印报错但是不影响使用

### ISSUE THREAD

**Issue by nanjunyu** [wuyouzhuguli/FEBS-Vue#31]
后端代码所有类中的 log.error(message, e); 等等idea报错;
log没有定义
但是不影响使用，强迫症看着很难受，
是我没配置什么东西，还是手动引用一下。

![image](https://user-images.githubusercontent.com/23097168/58222064-6f010a80-7d47-11e9-80f9-4d1d3d85df2a.png)

**Comment by wuyouzhuguli** [comment]
lombok插件
