### ISSUE TITLE
后端添加拦截器，controller无法解析实体对象

### ISSUE THREAD

**Issue by sssssssq** [wuyouzhuguli/FEBS-Vue#32]
你好，我在后端添加了自己的拦截器组之后，controller就无法解析实体对象，请问再怎么操作

**Comment by mxthd** [comment]
贴代码出来看看呀

**Comment by sssssssq** [comment]
@Configuration
public class MywebConfig implements WebMvcConfigurer {

    @Autowired
    MyInterceptor myInterceptor
    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(myInterceptor) 
                .addPathPatterns("/asd/**"); 
  }

自己定义了一个拦截器，然后配置了一下，在修改菜单的时候就后端就解析不到role对象

**Comment by mgzu** [comment]
最好能够提供 demo，这一段代码看不出问题
