### ISSUE TITLE
楼主可以给个在linux上后台启动的脚本吗

### ISSUE THREAD

**Issue by nanjunyu** [wuyouzhuguli/FEBS-Vue#33]
这个项目我在我的centos7.4 服务器安装好了node和yarn

有没有yarn start启动到后台停止的脚本 ，最好有生成日志文件的
另外这个配置写localhost不好，在线上不能访问，建议写成这样
![image](https://user-images.githubusercontent.com/23097168/58242435-63cad080-7d81-11e9-8a5e-6d4da859a870.png)

**Comment by wuyouzhuguli** [comment]
后端打成jar包部署，前端打包后部署在NG下，可以参考文档
