### ISSUE TITLE
首次登录需要输入两次账号信息

### ISSUE THREAD

**Issue by wsyxzxs** [wuyouzhuguli/FEBS-Vue#39]
在本地服务中，访问http://localhost:8081/#/login 输入账号和密码后，请求接口被取消了，页面刷新到http://localhost:8081/?#/login时，输入账号和密码就能成功登录。

**Comment by wuyouzhuguli** [comment]
没太明白

**Comment by wsyxzxs** [comment]
在login页面中，控制台出现了Warning: `fieldDecoratorId` is deprecated. please use `v-decorator={id, options}` instead. 我按照[ant-design-vue 官网 form组件](https://vue.ant.design/components/form-cn/)，使用v-decorator 代替fieldDecoratorId而产生的问题，不知道怎么修改才行。

**Comment by wsyxzxs** [comment]
> 没太明白

在login页面中，控制台出现了Warning: fieldDecoratorId is deprecated. please use v-decorator={id, options} instead. 我按照ant-design-vue 官网 form组件，使用v-decorator 代替fieldDecoratorId而产生的问题，不知道怎么修改才行。

**Comment by wuyouzhuguli** [comment]
告警不影响使用，我在演示环境上试了，没有出现需要输入两次账号信息才能登录的情况呀
