### ISSUE TITLE
有些接口前端往后端传递userId

### ISSUE THREAD

**Issue by nanjunyu** [wuyouzhuguli/FEBS-Vue#40]
有些接口前端往后端传递userId，比如修改个人资料user/profile接口

这样是不是不对，应该是从token里解析就可以了吧，不需要传userId吧

**Comment by wuyouzhuguli** [comment]
不传的话可以通过getCurrentUser来获取

**Comment by nanjunyu** [comment]
> 不传的话可以通过getCurrentUser来获取

谢谢  我试试
