### ISSUE TITLE
请问大神系统支持集群部署么？

### ISSUE THREAD

**Issue by yangguang111lll** [wuyouzhuguli/FEBS-Vue#42]
请问大神系统支持集群部署么？

**Comment by wuyouzhuguli** [comment]
可以，因为token存储在redis里，所以后端集群部署的话，需要将redis地址指向同一个redis服务（或者redis集群）。然后通过负载均衡转发前端请求到后端集群。

**Comment by wuyouzhuguli** [comment]
可以，因为token存储在redis里，所以后端集群部署的话，需要将redis地址指向同一个redis服务（或者redis集群）。然后通过负载均衡转发前端请求到后端集群。
