### ISSUE TITLE
服务降级问题

### ISSUE THREAD

**Issue by zuosc** [wuyouzhuguli/FEBS-Vue#45]
尝试了下，如果redis挂了，整个系统就异常了。

这样对redis进行了强依赖，是不合适的设计。

个人建议，可以搞下服务降级。

**Comment by wuyouzhuguli** [comment]
可以搭建Redis集群

**Comment by zuosc** [comment]
额 并不是这个意思。  我的意思是服务降级。 假设和redis的网络断了呢

**Comment by wuyouzhuguli** [comment]
如果真要考虑服务降级，那系统复杂度都高了，作为一个脚手架，我觉得还是不要太复杂为好。

**Comment by zuosc** [comment]
也是
