### ISSUE TITLE
为什么还要用数据库的function

### ISSUE THREAD

**Issue by xiao8Git** [wuyouzhuguli/FEBS-Vue#48]

**Comment by wuyouzhuguli** [comment]
比如？

**Comment by xiao8Git** [comment]
![image](https://user-images.githubusercontent.com/20312821/60077013-8a52a180-975b-11e9-87c7-4f7929e8cdc5.png)

**Comment by wuyouzhuguli** [comment]
mysql不支持树查询，只能通过函数实现了

**Comment by xiao8Git** [comment]
为什么不在java里实现？

**Comment by wuyouzhuguli** [comment]
有什么影响么?

**Comment by xiao8Git** [comment]
如果用数据中间件，可能不支持，聚合函数都不支持，只支持标准的sql，我看程序里有用mysql自己的函数，比如GROUP_CONCAT，group by 的写法也有问题，标准的group by 后只能select group by 的字段和聚合函数，其它mysql也有一个only_full_group_by开关，如果打开了字法就有问题

**Comment by wuyouzhuguli** [comment]
如果觉得不合理可以自个在Java里实现。

**Comment by mgzu** [comment]
确实会存在一些问题

**Comment by wuyouzhuguli** [comment]
近期修复，谢谢建议

**Comment by wuyouzhuguli** [comment]
已修复
