### ISSUE TITLE
项目启动报错：缓存初始化失败

### ISSUE THREAD

**Issue by zwdgit** [wuyouzhuguli/FEBS-Vue#5]
**错误日志：**

> ###Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'febs.u.USER_ID' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
###The error may exist in file [/Users/zhu_wd/workspace/FEBS-Vue-master/backend/target/classes/mapper/system/UserMapper.xml]
###The error may involve cc.mrbird.febs.system.dao.UserMapper.findUserDetail-Inline
###The error occurred while setting parameters
###SQL: SELECT         u.user_id userId,         u.username,         u.password,         u.email,         u.mobile,         u.STATUS,         u.create_time createTime,         u.ssex,         d.dept_id deptId,         d.dept_name deptName,         u.AVATAR,         u.DESCRIPTION,         u.LAST_LOGIN_TIME lastLoginTime,         GROUP_CONCAT(r.role_id) roleId,         GROUP_CONCAT(r.ROLE_NAME) roleName         FROM         t_user u         LEFT JOIN t_dept d ON (u.dept_id = d.dept_id)         LEFT JOIN t_user_role ur ON (u.user_id = ur.user_id)         LEFT JOIN t_role r ON r.role_id = ur.role_id         WHERE 1 = 1                                                                     group by u.username                           ORDER BY u.user_id
###Cause: java.sql.SQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'febs.u.USER_ID' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'febs.u.USER_ID' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**错误代码：**
cc.mrbird.febs.common.runner.CacheInitRunner
42行: 
List<User> list = this.userMapper.findUserDetail(null)
追踪到 UserMapper.xml 中的查询操作：

> < select id="findUserDetail" resultType="user" parameterType="user" >

**错误分析：**
违背 mysql 查询规则
https://blog.csdn.net/u010429286/article/details/64444271

**Comment by wuyouzhuguli** [comment]
两周前我已经更新了[SQL](https://github.com/wuyouzhuguli/FEBS-Vue/blob/master/sql/febs.sql)，最后两行SQL语句就是为了解决这个问题的，你复制执行下应该就好了。
