### ISSUE TITLE
能请教下如何加swagger吗

### ISSUE THREAD

**Issue by iot-hunter** [wuyouzhuguli/FEBS-Vue#51]
目前报错
 
![image](https://user-images.githubusercontent.com/13657036/60793487-626f2f00-a19a-11e9-8f9f-dfe31c937bcb.png)

**Comment by mgzu** [comment]
@iot-hunter  修改 application.yml，将 swagger 相关资源加入到 anonUrI 后.
例如：
```
anonUrl: /login,/logout/**,/regist,/user/check/**,/swagger-ui.html,/swagger-resources/**,/v2/api-docs,/webjars/springfox-swagger-ui/**
```
有问题建议使用搜素引擎搜索 swagger shiro spring boot 等关键字.

**Comment by iot-hunter** [comment]
依然还是这样
![image](https://user-images.githubusercontent.com/13657036/60797601-293abd00-a1a2-11e9-9ac8-c6774e82b394.png)
![image](https://user-images.githubusercontent.com/13657036/60797638-39529c80-a1a2-11e9-98ec-84ed57b0a72e.png)
![image](https://user-images.githubusercontent.com/13657036/60797652-41124100-a1a2-11e9-922e-45b18a666420.png)
