### ISSUE TITLE
登录页面中input样式设置在哪里?没办法重叠掉,好像是全局配置的

### ISSUE THREAD

**Issue by 609587174** [wuyouzhuguli/FEBS-Vue#52]

**Comment by wuyouzhuguli** [comment]
https://github.com/wuyouzhuguli/FEBS-Vue/blob/master/frontend/src/views/login/Login.vue

style里面不能改？

**Comment by 609587174** [comment]
之前在里面些也重叠不了,后面我自己写了给less文件全局应用就可以了,对了,你那个自适应浏览器窗口时,当窗口变小时,有样式错误

**Comment by wuyouzhuguli** [comment]
这个系统没做自适应布局嗷

**Comment by 609587174** [comment]
哈哈,没什么,就是发现这个问题,去掉就可以了
