### ISSUE TITLE
关于查询条件结果的问题

### ISSUE THREAD

**Issue by wsyxzxs** [wuyouzhuguli/FEBS-Vue#54]
这里只是举个例子：当我的数据量很大，比如我在用户管理列表中，当前页数是第 16页时，我搜索用户名为 【febs1234】的关键字时，接口会查询关键字，不过是查询页数为当前的十六页，此刻返回数据为空，给你一直没有该条数据的假象。如果查询接口页数当前页为第一页是，则可以正确显示结果。

**Comment by wuyouzhuguli** [comment]
你可以在查询方法里，将页码设置为1

**Comment by wsyxzxs** [comment]
的确可以这样子实现功能。如果当前页不是第一页，查询的结果同时为空时，我是否可以调用当前页上一页，直到有结果返回或者当前页为第一页时，这样的效果更好呢。

**Comment by wuyouzhuguli** [comment]
如果上一页也是空的呢？

**Comment by wsyxzxs** [comment]
上一页为空，再查询上上一页，如果查询为第一页或者有数据返回时，就停止调用查询呀

**Comment by wuyouzhuguli** [comment]
如果你现在在第1000页，查询某个数据，返回只有1条（也就是第一页），那你要调用999次查询？

**Comment by wsyxzxs** [comment]
这样效果不太友好了，如果直接访问第一页，用户体验感不是很好，毕竟也可以在查询1000页时，999页也有结果的情况

**Comment by wuyouzhuguli** [comment]
行吧......
