### ISSUE TITLE
新增角色cs，分配权限菜单系统管理下的用户管理，添加成功后，角色为cs的用户csyh，登录成功后无用户管理菜单

### ISSUE THREAD

**Issue by gitspringcould** [wuyouzhuguli/FEBS-Vue#56]

**Comment by wuyouzhuguli** [comment]
本地试了没有出现你说的情况

**Comment by gitspringcould** [comment]
是不是添加的时候父子关联了呢




------------------ 原始邮件 ------------------
发件人: "mrbird"<notifications@github.com>;
发送时间: 2019年7月26日(星期五) 中午1:58
收件人: "wuyouzhuguli/FEBS-Vue"<FEBS-Vue@noreply.github.com>;
抄送: "何某人"<1162487568@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wuyouzhuguli/FEBS-Vue] 新增角色cs，分配权限菜单系统管理下的用户管理，添加成功后，角色为cs的用户csyh，登录成功后无用户管理菜单 (#56)




本地试了没有出现你说的情况

**Comment by wuyouzhuguli** [comment]
没有管理，可以debug看下登录成功后用户是否获取到了相应的菜单

**Comment by mgzu** [comment]
@gitspringcould @wuyouzhuguli 这个 bug 发生在新增角色时只勾选二级目录，没勾选一级目录 : )
![20190727144232](https://user-images.githubusercontent.com/29629221/61990994-cc357700-b07c-11e9-9ca0-0d555d030a1e.png)

**Comment by mgzu** [comment]
@gitspringcould @wuyouzhuguli 这个 bug 发生在新增角色时只勾选二级目录，没勾选一级目录 : )
![20190727144232](https://user-images.githubusercontent.com/29629221/61990994-cc357700-b07c-11e9-9ca0-0d555d030a1e.png)

**Comment by gitspringcould** [comment]
嗯嗯，是的，父子没有关联后台查询的时候就不会有一级菜单




------------------ 原始邮件 ------------------
发件人: "Ma Guang Zu"<notifications@github.com>;
发送时间: 2019年7月27日(星期六) 下午2:45
收件人: "wuyouzhuguli/FEBS-Vue"<FEBS-Vue@noreply.github.com>;
抄送: "何某人"<1162487568@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wuyouzhuguli/FEBS-Vue] 新增角色cs，分配权限菜单系统管理下的用户管理，添加成功后，角色为cs的用户csyh，登录成功后无用户管理菜单 (#56)




@gitspringcould @wuyouzhuguli 这个 bug 发生在新增角色时只勾选二级目录，没勾选一级目录 : )

**Comment by wuyouzhuguli** [comment]
上级肯定是要勾选的，没有上级下级自然也没有
