### ISSUE TITLE
就路由守卫功能相关的

### ISSUE THREAD

**Issue by 609587174** [wuyouzhuguli/FEBS-Vue#58]
我现在有个列表页,想要点击列表其中一条数据跳转到详情页,但是不想在菜单同级处增多一个列表详情( 因为这页面要是不通过点击列表名称进入的话是没数据的 ),该怎么做,之前我页面路由都是写好的,现在变成这种系统返回的,还真一时想不出好办法

**Comment by 609587174** [comment]
而且正常这个列表详情也是属于列表页的子集,只是不用在菜单里显示出来

**Comment by wuyouzhuguli** [comment]
路由可以设置为隐藏，这样就不会在菜单上显示了

**Comment by 609587174** [comment]
你说的过滤隐藏,是不是在GlobalLayout.vue页面菜单拿路由数据渲染时过滤掉?

**Comment by wuyouzhuguli** [comment]
https://mrbird.cc/FEBS-Vue-Document.html 参考如何隐藏路由
