### ISSUE TITLE
左边菜单栏不见了

### ISSUE THREAD

**Issue by wsyxzxs** [wuyouzhuguli/FEBS-Vue#59]
登录进来，关闭浏览器时，重新访问,浏览器的 localStorage 中的数据还在，我重新访问项目路径，直接到达系统主页，没有登录，我怎么让它登录一下呢，有时候访问主页时，左边栏不见了

**Comment by wuyouzhuguli** [comment]
如果关闭浏览器登录也要失效的话，可以使用SessionStorage替换localStorage

**Comment by wsyxzxs** [comment]
谢谢提醒
