### ISSUE TITLE
文档内容收集

### ISSUE THREAD

**Issue by wuyouzhuguli** [wuyouzhuguli/FEBS-Vue#7]
文档都需要包含哪些内容？欢迎讨论。

初版文档：[https://mrbird.cc/FEBS-Vue-Document.html](https://mrbird.cc/FEBS-Vue-Document.html)

**Comment by yuuki80code** [comment]
出个视频，从安装node环境开始，怎么做的前端，后台怎么设计，最好露脸

**Comment by sixpence0112** [comment]
vue详细介绍一下

**Comment by tang1998bjt** [comment]
从盘古开天辟地开始吧

**Comment by lovrth** [comment]
加个swagger吧

**Comment by wuyouzhuguli** [comment]
> 加个swagger吧

swagger代码耦合度较高，有需要可以自己添加

**Comment by huluobo11** [comment]
关键是不会vue,55555

**Comment by jiashuai333** [comment]
文档的话，配置方面介绍一下，一些技术上加上注释就更好啦，每个类是干嘛的哈哈

**Comment by kun910202** [comment]
最好能优化下首次加载，移动版的可以有吗

**Comment by yourmonboom** [comment]
最好能提供一下mybatis-generator生成的教程,哈哈

**Comment by wszpf007** [comment]
详细介绍下使用vue的开发过程，还有shiro+jwt的整合过程

**Comment by lijiazhi** [comment]
加个记住密码和图片验证码吧

**Comment by wszpf007** [comment]
把里面的任务调度的设计思想讲讲

**Comment by long0419** [comment]
把代码生成这块加上 最好了

**Comment by ackermanzhang** [comment]
能否优化下首页加载，折腾了很久，发现也要9s左右，辛苦辛苦。

**Comment by dhm123** [comment]
只能说非常好了   目前vue可以说是必须要了解的了

**Comment by xinxin23** [comment]
如果可以的话，文档里面能够加入**无前端情况下后台接口调试教程**和**无后端情况下前端样式调试教程**。

**Comment by 2229499815** [comment]
我看上你的前端了，可以拿来用吗？你这套前端设计的很有水准，考虑了美观以及便捷性。
